### ISSUE TITLE
Earn

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#1459]
# Acceptance criteria
[Economic completeness](https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Economic-Completeness_suVk6#_lupDk) 

# TBD/needs spike/blocked/wait
- [ ] earn slice vs doggo service refactor/design
- [x] Pool deposit icons: Where do they come from?
- [x] Does it worth it to use Uniswap SDK instead of manually calculating the APR for LP pools?

# Dependencies
- [ ] Some parts of the design are WIP: https://github.com/tallycash/Product-Design/issues/1
- [ ] ⚠️ Missing strategies: we need time to integrate and test to be sure after we have them
  - We will need time, after we have them, for integration and testing
- https://github.com/tallycash/contracts/issues/225

# Decisions
- ~$DOGGO service hardcode vault addresses (later fetching from the hunting ground registry)~
  - > We will need to grab the hunting grounds from the registry before we can release earn
- We are implementing the sad version of the design

# Work Breakdown

- [ ] #1536
- [ ] tallycash/extension#1471 
- [ ] #1538
- [ ] tallycash/extension#1460
- [ ] https://github.com/tallycash/extension/issues/1466
- [ ] tallycash/extension#1458
- [ ] #1539
- [ ] https://github.com/tallycash/extension/issues/1519
- [ ] https://github.com/tallycash/extension/issues/1527
- [ ] https://github.com/tallycash/extension/issues/1528
- [x] tallycash/extension#1474 
- [ ] https://github.com/tallycash/extension/issues/1535

# Done 

- [x] tallycash/extension#1461
- [x] tallycash/extension#1476 
- [x] tallycash/tally-extension-token#215
  - [figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=9484%3A158736)
- [x] tallycash/tally-extension-token#211
  - [ ] https://github.com/tallycash/extension/pull/1325 - should be built on top of this PR
- [x] tallycash/tally-extension-token#182 
- [x] tallycash/tally-extension-token#216
  - [figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A146317)
- [x] tallycash/tally-extension-token#217
  - [deposit page](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A146353)
  - [empty page](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A146488)
- [x] tallycash/tally-extension-token#218
- [x] tallycash/tally-extension-token#214
- [x] tallycash/tally-extension-token#219
- [x] tallycash/tally-extension-token#220
- [x] tallycash/tally-extension-token#213 
- [x] tallycash/tally-extension-token#206 
- [x] tallycash/tally-extension-token#238 
- [x] tallycash/tally-extension-token#192 
- [x] tallycash/tally-extension-token#180 
- [x] tallycash/tally-extension-token#163 
- [x] tallycash/tally-extension-token#159 
- [x] tallycash/tally-extension-token#158 
- [x] tallycash/tally-extension-token#58 
- [x] tallycash/tally-extension-token#253
