### ISSUE TITLE
Earn and claim phases depending on contracts

### ISSUE THREAD

**Issue by greg-nagy** [tallyhowallet/extension#1466]
# Context
* [Original idea scoped to deploy contracts thread](https://www.flowdock.com/app/cardforcoin/tally/threads/SBqYT4haeN6lnqNk1VCGK8cCZLg)
* [Extended idea](https://www.flowdock.com/app/cardforcoin/tech/threads/-q1FOvi1ahsYFbGqStTMlJuWoUi)
* [Final verification](https://www.flowdock.com/app/cardforcoin/tally/threads/VsbCYtJr2_h1_dLoBL0AlBnYAFB)
* [Meta commentary](https://www.flowdock.com/app/cardforcoin/tally/threads/qaYseiufDcuN-oAaEQTJRO3MgEY)

# Design
[Figma Link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=9935%3A153166)

# Work breakdown

### UI elements

- [x] Coming soon header section (Pre deploy)
- [x] Deploying contracts header section
- [x] "Before you get started" banner
- [ ] "Launching in" timer ready to be connected to real data
- [ ] ~~TVL chart in the background~~ (optional, can be done later)
- [ ] connecting each phase with contracts state (breakdown below)

### Phase 1 - Contracts not public
> API `https://api.github.com/repos/tallycash/contracts`
If the contract repo is _NOT_ public, show:
1. Handle displaying this "Deploy contract" page on earn tab
<img width="209" alt="earn phase one" src="https://user-images.githubusercontent.com/80846886/167462508-ce61260f-c67d-4a60-a330-998d39f2680a.png">
2. <b>Claim flow private</b>

 ### Phase 2 - Contracts public, not all contracts deployed
 
<img width="213" alt="earn phase two" src="https://user-images.githubusercontent.com/80846886/167462755-ee941da0-bea7-4170-89a0-65b7b82dec1d.png">

Contracts are being deployed, but not all yet
 1. Load the `deployment-info.json` from the contracts repo and parse it for contract addresses
     - IF (contracts opensource) THEN fetch `deployment-info.json` AND  use address ELSE use hardcoded values
     - Move the hardcodeing of the addresses into environment variables from the code 

2. Whenever claim contracts live, make **claim flow public**

 ### Phase 3 - Contracts deployed, pool launch countdowns
 Contracts deployed, but not all pools are launched yet.
 - Check `deployment-info.json`
 - Countdown on individual pools for launch
 
<img width="214" alt="Earn phase 3" src="https://user-images.githubusercontent.com/80846886/167462716-279b3c83-1d4c-4d0c-9ee0-9272eeea884e.png">
