### ISSUE TITLE
Claim flow (Claim + Referrals)

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#1470]
In economic completeness doc it has 2 sections 
- [Claim](https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Economic-Completeness-05-2022_suVk6#_luFxN)
- [Referrals](https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Economic-Completeness-05-2022_suVk6#_lucWO)

From dev perspective it makes more sense to track them together because they are intertwined.

# Work breakdown
- [ ] #1540
- [x] tallycash/extension#1461
- [ ] tallycash/extension#1473
- [x] https://github.com/tallycash/tally-extension-token/issues/193
- [ ] tallycash/extension#1475
- [ ] tallycash/tally.cash-token#4
- [ ] tallycash/extension#1457
- [ ] tallycash/extension#1456
- [ ] tallycash/tally.cash-token#3
- [x] https://github.com/tallycash/extension/issues/1535
- [ ] #1537

Blocked:
- [x] tallycash/product-design#21
- [ ] tallycash/extension#1454
- [ ] tallycash/extension#1463
