### ISSUE TITLE
Overview page update

### ISSUE THREAD

**Issue by jagodarybacka** [tallyhowallet/extension#1931]
- [x] https://github.com/tallycash/extension/issues/1932
- [x] https://github.com/tallycash/extension/issues/1933
- [x] https://github.com/tallycash/extension/issues/1934

---
The overview page got a new design with a networks stats breakdown
<img width="572" alt="image" src="https://user-images.githubusercontent.com/20949277/184373512-9533e8fe-496c-407f-b4fc-fcb6a35f100f.png">
