### ISSUE TITLE
Alchemy rate limiting issues

### ISSUE THREAD

**Issue by puppycodes** [tallyhowallet/extension#2034]
- [x] Determine if the alchemy `getAssetTransfers` API has matured enough since we first implemented it last year to reduce the number of calls we need to make.
- [x] #2044
- [x] #2059
- [ ] Move our codebase away from relying on periodic calls to getAssetTransfers as a bandaid for possibly missing incoming transactions.
- [x]  Audit our use of alchemy calls and see where else we can decrease dependency on or frequency of alchemy calls.
- [x] Switch `handleRecentAssetTransferAlarm` to a backoff retry mechanism

**Comment by 0xDaedalus** [comment]
Although we still rely on periodic calls to `getAssetTransfers` for reconcilliation - we have decided that relying on it moving forward  is a happy path so closing this issue as completed
