### ISSUE TITLE
Ledger support

### ISSUE THREAD

**Issue by mr-michael** [tallyhowallet/extension#496]
This is the tracking issue, for the Ledger support development.

## Feature pitch
⚠️ WIP 

## Design
 [Ledger Figma link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/?node-id=3084%3A94958)
- [x] #815 
- [x] #827 

## Technical RFC
https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/RFC-Hardware-wallet-signers_susPg#_lu2al

# Discovery / Research / Spike
- [x] What parts can we use from `ledgerjs` and `ledger-live-common`: 
  - @ledgerhq/hw-transport-webauthn@5.36.0-deprecated
  - @ledgerhq/hw-transport-webusb
  - @ledgerhq/hw-transport
  - @ledgerhq/hw-app-eth
  - communication specific parts from [ledger-live-common](https://github.com/LedgerHQ/ledger-live-common/tree/master/src/hw) (does not contain RxJS)
- [x] Initial ledger communication testing
  - [x] webauthn communication on firefox
  - [x] webusb transport layer test on chrome 
    - [x] get information about the ledger
    - [x] read addresses from the ledger
    - [x] test transaction signing 
- [ ] check what/how can we utilise higher level extra functionality from `ledger-live-common`
  - [ ] is the device genuine check
  - [ ] ...

### 02.07 - 02.11
- [x] #921
- [x] #841
- [x] #934 :: Massimo
- [ ] #951
- [x] #952

### 01.31 - 02.04

- [x] #918
  - #838
    - create Ledger service
    - create Signing Service
  - #839 
    - connection handling
    - get device info 
    - get addresses
    - sign transaction
- [x] #919
- implement the missing pieces of the UI
  - [x] #920 
  - [x] #921
  - [x] #841
- [x] update unlock behavior for keyring service to happen after the user clicks "Sign"
  - https://github.com/tallycash/extension/pull/910#discussion_r794455688

### Backlog

- [ ] webauthn / FF
  - connection handling
  - get device info 
  - get addresses
  - sign transaction
- [ ] ❓ remove tab entry point and use the ui entry point with query params (if there is no good reason for it to exist)

### Done

- [x] #840
  - create signing redux slice
  - add new import wallet item for ledger
  - open new tab
  - implement browser detection 
- [x] #850
- [x] #852
- [x] #851
- [x] https://github.com/tallycash/extension/pull/899#discussion_r792667593
- [x] #840
  - create signing redux slice
  - add new import wallet item for ledger
  - open new tab
  - implement browser detection 
- [x] #850
- [x] #852
- [x] #851

Related tickets:
- [x] #336 
- [x] #337

**Comment by mhluongo** [comment]
Closing this in favor of #337 and #336. They both are referenced by some of my existing Ledger work

**Comment by greg-nagy** [comment]
Reopening this issue, to serve as a tracking ticket for work planning and work break down

**Comment by 0xDaedalus** [comment]
Closed b/c stale and complete
